#!/usr/bin/env bash

source $(dirname $0)/helpers.sh
LOG=/tmp/log/$(basename $0).log
mkdir -p /tmp/log

DOMAIN=$1
USER=vagrant

(
    display Starting build at $(date)

    display Install Developer packages
    (
        xargs apt-get install -y < $(dirname $0)/packages.txt
    ) 2>&1 | indent

    display Install Docker
    (
        curl -sSL https://get.docker.io/ubuntu/ | sh
        usermod -a -G docker "$USER"
    ) 2>&1 | indent 

) 2>&1 | tee $LOG


display "Ready to go!"
